[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = []

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
